FROM node:20.10.0-alpine as build-stage

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY ./frontend/package.json /app/package.json

RUN yarn install

COPY ./frontend /app

CMD ["yarn", "start"]