name: serhii_sorochinskii CI

on:
  pull_request:
    branches:
      - master
      - main
      - develop

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      IS_TEST_DATABASE: True

    steps:
      - uses: actions/checkout@v2
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-root

      - name: Show pytest.ini
        run: cat pytest.ini
      
      - name: Run tests
        run: |
          export PYTHONPATH=backend/src
          poetry run pytest backend/src/tests


  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          
      - name: Run Flake8
        run: |
          flake8 --config .flake8
